image: Visual Studio 2019
before_build:
  nuget restore
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: minimal
after_build:
  dotnet pack /p:PackageVersion=%appveyor_build_version% Apcupsd.NET
artifacts:
  path: '**\Apcupsd.NET.*.nupkg'
